// web/src/components/TopScorers.tsx
import { useState } from 'react'
import type { TopScorer, TopScorerBet } from '../types'
import { getCountry } from '../countries'
import { Flag } from './Flag'

interface TopScorersProps {
  scorers: TopScorer[]
  bets: TopScorerBet[]
}

export function TopScorers({ scorers, bets }: TopScorersProps) {
  const [open, setOpen] = useState(true)

  const predictedPlayers = new Set(bets.map((b) => b.player))
  const sorted = [...scorers].sort((a, b) => b.goals - a.goals)

  return (
    <section className="standings-section">
      <button className="section-toggle" onClick={() => setOpen((o) => !o)}>
        <h2 className="section-title">Top Scorers</h2>
        <span className="toggle-icon">{open ? '▲' : '▼'}</span>
      </button>
      {open && (
        <div className="top-scorers-wrap">
          <table className="top-scorers-table">
            <thead>
              <tr>
                <th className="col-rank">#</th>
                <th className="col-ts-player">Player</th>
                <th className="col-ts-team">Team</th>
                <th>Goals</th>
                <th>Games</th>
              </tr>
            </thead>
            <tbody>
              {sorted.map((s, i) => {
                const { fi } = getCountry(s.team)
                const isPredicted = predictedPlayers.has(s.player)
                return (
                  <tr
                    key={`${s.player}-${s.team}`}
                    className={[
                      s.team_eliminated ? 'scorer-eliminated' : '',
                      isPredicted       ? 'scorer-predicted'  : '',
                    ].filter(Boolean).join(' ')}
                  >
                    <td className="col-rank">{i + 1}</td>
                    <td className="col-ts-player">
                      {s.player}
                      {isPredicted && <span className="scorer-bet-marker" title="Bet placed on this player"> ★</span>}
                    </td>
                    <td className="col-ts-team">
                      <Flag fi={fi} className="team-flag" />
                      {s.team}
                    </td>
                    <td className="col-goals">{s.goals}</td>
                    <td>{s.games}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}
    </section>
  )
}

// web/src/components/TopScorers.svelte
<script lang="ts">
  import type { TopScorer, TopScorerBet } from '../types'
  import { getCountry } from '../countries'
  import Flag from './Flag.svelte'

  interface Props {
    scorers: TopScorer[]
    bets: TopScorerBet[]
  }

  let { scorers, bets }: Props = $props()
  let open = $state(true)

  let predictedPlayers = $derived(new Set(bets.map((b) => b.player)))
  let sorted = $derived([...scorers].sort((a, b) => b.goals - a.goals))
</script>

<section class="standings-section">
  <button class="section-toggle" onclick={() => (open = !open)}>
    <h2 class="section-title">Top Scorers</h2>
    <span class="toggle-icon">{open ? '▲' : '▼'}</span>
  </button>
  {#if open}
    <div class="top-scorers-wrap">
      <table class="top-scorers-table">
        <thead>
          <tr>
            <th class="col-rank">#</th>
            <th class="col-ts-player">Player</th>
            <th class="col-ts-team">Team</th>
            <th>Goals</th>
            <th>Games</th>
          </tr>
        </thead>
        <tbody>
          {#each sorted as s, i}
            {@const { fi } = getCountry(s.team)}
            {@const isPredicted = predictedPlayers.has(s.player)}
            <tr class={[s.team_eliminated ? 'scorer-eliminated' : '', isPredicted ? 'scorer-predicted' : ''].filter(Boolean).join(' ')}>
              <td class="col-rank">{i + 1}</td>
              <td class="col-ts-player">
                {s.player}
                {#if isPredicted}
                  <span class="scorer-bet-marker" title="Bet placed on this player"> ★</span>
                {/if}
              </td>
              <td class="col-ts-team">
                <Flag {fi} class="team-flag" />
                {s.team}
              </td>
              <td class="col-goals">{s.goals}</td>
              <td>{s.games}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>
